name: Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: vishnu18032
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
    - name: Build with Maven
      run: ./mvnw clean install
    - name: Run tests
      run: ./mvnw test
